package com.joantolos.utils.enums;

public enum FileErrorCode {
	OK,
    CLOSING_BUFFERED_READER_ERROR,
    CLOSING_INPUT_STREAM_ERROR,
    FILE_ARRAY_BYTES_NULL,
    UNMARSHALLING_FILE_ERROR,
    STRING_FROM_STREAM_ERROR,
    WRITING_FILE_ERROR,
    DELETING_FILE_ERROR
}
